server:
  port: 8083
  servlet:
    context-path: /auth

spring:
  application:
    name: auth
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQL9Dialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/auth
    username: postgres
    password: 1234
security:
  jwt:
    token:
      secret-key: chave_secreta
      expire-length: 360000

